import localFont from "next/font/local";
import "./globals.css";

import Sidebar from "@/components/common/Sidebar";
import BreadCrumb from "@/components/reuseableComponent/BreadCrumb";
import Navbar from "@/components/common/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <main className="flex w-[100%] justify-between">
            <div className="hidden sm:block">
              <Sidebar />
            </div>
            <div className="w-[100%] overflow-x-hidden">
              <div>
                <Navbar />
              </div>
              <div>
                <BreadCrumb />
              </div>
              <div>{children}</div>
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
